"""FATF Regulator Pack - Financial Action Task Force."""
from regulator_packs.base_pack import (
    RegulatorPack, JurisdictionDef, RegulatorDef, SourceDef, TopicDef, ProvisionFixture,
)


def get_pack() -> RegulatorPack:
    return RegulatorPack(
        pack_id="fatf",
        jurisdiction=JurisdictionDef(
            name="International",
            code="INTL",
            name_ar="دولي",
            region="International",
        ),
        regulator=RegulatorDef(
            name="Financial Action Task Force",
            abbreviation="FATF",
            name_ar="مجموعة العمل المالي",
            website="https://www.fatf-gafi.org",
            source_url="https://www.fatf-gafi.org/en/recommendations.html",
            regulator_type="international_standard_setter",
            description="International body setting AML/CTF standards",
            description_ar="هيئة دولية لوضع معايير مكافحة غسل الأموال وتمويل الإرهاب",
        ),
        sources=[
            SourceDef(
                title="FATF 40 Recommendations",
                key="fatf_40_recommendations",
                title_ar="توصيات مجموعة العمل المالي الأربعون",
                url="https://www.fatf-gafi.org/en/topics/fatf-recommendations.html",
                source_type="regulation",
                authority_level="tier_1",
                language="en",
                crawl_frequency="monthly",
                topic_names=["Customer Due Diligence", "Enhanced Due Diligence", "Beneficial Ownership",
                             "Suspicious Transaction Reporting", "Risk-Based Approach",
                             "Targeted Financial Sanctions", "Wire Transfer Transparency",
                             "Correspondent Banking", "Politically Exposed Persons", "New Technologies"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="FATF Guidance on Risk-Based Approach",
                key="fatf_rba_guidance",
                title_ar="إرشادات مجموعة العمل المالي بشأن النهج القائم على المخاطر",
                url="https://www.fatf-gafi.org/en/topics/risk-based-approach.html",
                source_type="guidance",
                authority_level="tier_2",
                language="en",
                crawl_frequency="monthly",
                topic_names=["Risk-Based Approach", "Customer Due Diligence"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="FATF Guidance on Virtual Assets and VASPs",
                key="fatf_va_vasps_guidance",
                title_ar="إرشادات مجموعة العمل المالي بشأن الأصول الافتراضية",
                url="https://www.fatf-gafi.org/en/topics/virtual-assets.html",
                source_type="guidance",
                authority_level="tier_2",
                language="en",
                crawl_frequency="monthly",
                topic_names=["New Technologies", "Risk-Based Approach"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="FATF Guidance on Beneficial Ownership",
                key="fatf_bo_guidance",
                title_ar="إرشادات مجموعة العمل المالي بشأن الملكية النفعية",
                url="https://www.fatf-gafi.org/en/topics/beneficial-ownership.html",
                source_type="guidance",
                authority_level="tier_2",
                language="en",
                crawl_frequency="monthly",
                topic_names=["Beneficial Ownership", "Customer Due Diligence"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
        ],
        topics=[
            TopicDef(name="Customer Due Diligence", category="kyc", name_ar="العناية الواجبة بالعملاء"),
            TopicDef(name="Enhanced Due Diligence", category="kyc", name_ar="العناية الواجبة المعززة"),
            TopicDef(name="Beneficial Ownership", category="kyc", name_ar="الملكية النفعية"),
            TopicDef(name="Suspicious Transaction Reporting", category="reporting", name_ar="الإبلاغ عن المعاملات المشبوهة"),
            TopicDef(name="Risk-Based Approach", category="aml", name_ar="النهج القائم على المخاطر"),
            TopicDef(name="Targeted Financial Sanctions", category="sanctions", name_ar="العقوبات المالية المستهدفة"),
            TopicDef(name="Wire Transfer Transparency", category="aml", name_ar="شفافية التحويلات البرقية"),
            TopicDef(name="Correspondent Banking", category="aml", name_ar="المراسلات المصرفية"),
            TopicDef(name="Politically Exposed Persons", category="pep", name_ar="الأشخاص المعرضون سياسياً"),
            TopicDef(name="New Technologies", category="fintech", name_ar="التقنيات الحديثة"),
        ],
        sample_provisions=[
            ProvisionFixture(
                section_number="R.10",
                title="Customer Due Diligence",
                title_ar="العناية الواجبة بالعملاء",
                text="Financial institutions should be required to undertake customer due diligence (CDD) measures when: (i) establishing business relations; (ii) carrying out occasional transactions above the applicable designated threshold (USD/EUR 15,000); (iii) there is a suspicion of money laundering or terrorist financing; or (iv) the financial institution has doubts about the veracity or adequacy of previously obtained customer identification data.",
                text_ar="يجب أن تُلزم المؤسسات المالية باتخاذ تدابير العناية الواجبة تجاه العملاء عند: (أ) إقامة علاقات عمل؛ (ب) تنفيذ معاملات عرضية تتجاوز الحد المعين (15,000 دولار أمريكي/يورو)؛ (ج) وجود اشتباه بغسل الأموال أو تمويل الإرهاب؛ أو (د) وجود شكوك حول صحة أو كفاية بيانات تعريف العميل التي تم الحصول عليها سابقاً.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="R.20",
                title="Reporting of Suspicious Transactions",
                title_ar="الإبلاغ عن المعاملات المشبوهة",
                text="If a financial institution suspects or has reasonable grounds to suspect that funds are the proceeds of a criminal activity, or are related to terrorist financing, it should be required, by law, to report promptly its suspicions to the financial intelligence unit (FIU).",
                text_ar="إذا اشتبهت مؤسسة مالية أو كانت لديها أسباب معقولة للاشتباه بأن الأموال هي عائدات نشاط إجرامي أو مرتبطة بتمويل الإرهاب، يجب أن يُلزمها القانون بالإبلاغ فوراً عن شبهاتها إلى وحدة التحريات المالية.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="R.6",
                title="Targeted Financial Sanctions related to Terrorism and Terrorist Financing",
                title_ar="العقوبات المالية المستهدفة المتعلقة بالإرهاب وتمويل الإرهاب",
                text="Countries should implement targeted financial sanctions regimes to comply with United Nations Security Council resolutions relating to the prevention and suppression of terrorism and terrorist financing. The resolutions require countries to freeze without delay the funds or other assets of, and to ensure that no funds or other assets are made available, directly or indirectly, to or for the benefit of, any person or entity designated by, or under the authority of, the United Nations Security Council.",
                text_ar="يجب على الدول تطبيق أنظمة العقوبات المالية المستهدفة للامتثال لقرارات مجلس الأمن الدولي المتعلقة بمنع الإرهاب وتمويل الإرهاب وقمعهما. تتطلب القرارات من الدول تجميد الأموال أو الأصول الأخرى فوراً وضمان عدم إتاحة أي أموال أو أصول أخرى بشكل مباشر أو غير مباشر لأي شخص أو كيان معين من قبل مجلس الأمن الدولي.",
                provision_type="article",
            ),
        ],
    )
