"""SAMA Regulator Pack - Saudi Central Bank (formerly SAMA)."""
from regulator_packs.base_pack import (
    RegulatorPack, JurisdictionDef, RegulatorDef, SourceDef, TopicDef, ProvisionFixture,
)


def get_pack() -> RegulatorPack:
    return RegulatorPack(
        pack_id="sama",
        jurisdiction=JurisdictionDef(
            name="Kingdom of Saudi Arabia",
            code="SA",
            name_ar="المملكة العربية السعودية",
            region="Middle East",
        ),
        regulator=RegulatorDef(
            name="Saudi Central Bank",
            abbreviation="SAMA",
            name_ar="البنك المركزي السعودي",
            website="https://www.sama.gov.sa",
            source_url="https://rulebook.sama.gov.sa",
            regulator_type="central_bank",
            description="Saudi Central Bank - primary regulator of banks, insurance, finance companies, and payment service providers in the Kingdom",
            description_ar="البنك المركزي السعودي - الجهة التنظيمية الرئيسية للبنوك وشركات التأمين وشركات التمويل ومقدمي خدمات الدفع في المملكة",
        ),
        sources=[
            SourceDef(
                title="SAMA AML/CTF Rules (Rulebook)",
                key="sama_aml_ctf_rules",
                title_ar="قواعد مكافحة غسل الأموال وتمويل الإرهاب - البنك المركزي",
                url="https://rulebook.sama.gov.sa/en/anti-money-laundering-counter-terrorist-financing-rules",
                source_type="rulebook",
                authority_level="tier_1",
                language="en",
                crawl_frequency="weekly",
                topic_names=["AML/CTF Compliance (SAMA)", "KYC and Account Opening (SAMA)",
                             "Transaction Monitoring (SAMA)", "Sanctions Screening (SAMA)",
                             "STR Filing (SAMA)", "Compliance Governance (SAMA)",
                             "Correspondent Banking (SAMA)"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="SAMA Anti-Fraud Rules",
                key="sama_anti_fraud_rules",
                title_ar="قواعد مكافحة الاحتيال - البنك المركزي",
                url="https://rulebook.sama.gov.sa/en/anti-fraud-rules",
                source_type="rulebook",
                authority_level="tier_1",
                language="en",
                crawl_frequency="weekly",
                topic_names=["Anti-Fraud (SAMA)", "Transaction Monitoring (SAMA)"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="SAMA Regulatory Sandbox Framework",
                key="sama_sandbox_framework",
                title_ar="إطار البيئة التنظيمية التجريبية - البنك المركزي",
                url="https://www.sama.gov.sa/en-US/RegulatoryFramework",
                source_type="guidance",
                authority_level="tier_2",
                language="en",
                crawl_frequency="monthly",
                topic_names=["Fintech Compliance (SAMA)"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="SAMA Rules on Opening Bank Accounts (KYC)",
                key="sama_kyc_account_rules",
                title_ar="قواعد فتح الحسابات المصرفية (اعرف عميلك)",
                url="https://rulebook.sama.gov.sa/en/rules-on-opening-bank-accounts",
                source_type="rulebook",
                authority_level="tier_1",
                language="en",
                crawl_frequency="weekly",
                topic_names=["KYC and Account Opening (SAMA)", "AML/CTF Compliance (SAMA)"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="SAMA Compliance and AML Circulars",
                key="sama_aml_circulars",
                title_ar="تعميمات الالتزام ومكافحة غسل الأموال - البنك المركزي",
                url="https://www.sama.gov.sa/en-US/Laws",
                source_type="circular",
                authority_level="tier_1",
                language="en",
                crawl_frequency="daily",
                topic_names=["AML/CTF Compliance (SAMA)", "Compliance Governance (SAMA)"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
            SourceDef(
                title="SAMA Fintech Regulations",
                key="sama_fintech_regs",
                title_ar="تنظيمات التقنية المالية - البنك المركزي",
                url="https://rulebook.sama.gov.sa/en/fintech",
                source_type="regulation",
                authority_level="tier_1",
                language="en",
                crawl_frequency="weekly",
                topic_names=["Fintech Compliance (SAMA)", "Payment Services Compliance (SAMA)"],
                parser_config={"parser_type": "html", "language": "en"},
            ),
        ],
        topics=[
            TopicDef(name="AML/CTF Compliance (SAMA)", category="aml", name_ar="الالتزام بمكافحة غسل الأموال وتمويل الإرهاب"),
            TopicDef(name="KYC and Account Opening (SAMA)", category="kyc", name_ar="اعرف عميلك وفتح الحسابات"),
            TopicDef(name="Transaction Monitoring (SAMA)", category="aml", name_ar="مراقبة العمليات"),
            TopicDef(name="Sanctions Screening (SAMA)", category="sanctions", name_ar="فحص العقوبات"),
            TopicDef(name="STR Filing (SAMA)", category="reporting", name_ar="الإبلاغ عن العمليات المشبوهة"),
            TopicDef(name="Compliance Governance (SAMA)", category="governance", name_ar="حوكمة الالتزام"),
            TopicDef(name="Fintech Compliance (SAMA)", category="fintech", name_ar="التزام التقنية المالية"),
            TopicDef(name="Payment Services Compliance (SAMA)", category="fintech", name_ar="التزام خدمات الدفع"),
            TopicDef(name="Anti-Fraud (SAMA)", category="aml", name_ar="مكافحة الاحتيال"),
            TopicDef(name="Correspondent Banking (SAMA)", category="aml", name_ar="المراسلات المصرفية"),
        ],
        sample_provisions=[
            ProvisionFixture(
                section_number="AML-1.1",
                title="Scope and Application",
                title_ar="النطاق والتطبيق",
                text="These Rules apply to all financial institutions (FIs) licensed by SAMA, including but not limited to: banks, finance companies, insurance and reinsurance companies, insurance brokers, payment service providers, money exchange businesses, and any other entities licensed or authorized by SAMA. All FIs shall comply with these Rules in addition to the Anti-Money Laundering Law and its Implementing Regulations.",
                text_ar="تسري هذه القواعد على جميع المؤسسات المالية المرخصة من البنك المركزي السعودي، بما في ذلك على سبيل المثال لا الحصر: البنوك وشركات التمويل وشركات التأمين وإعادة التأمين ووسطاء التأمين ومقدمي خدمات الدفع ومنشآت الصرافة وأي كيانات أخرى مرخصة من البنك المركزي.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="AML-2.1",
                title="Customer Due Diligence Requirements",
                title_ar="متطلبات العناية الواجبة بالعملاء",
                text="Financial institutions shall apply CDD measures when: (a) establishing a business relationship; (b) carrying out an occasional transaction above SAR 60,000; (c) carrying out occasional wire transfers above SAR 3,000; (d) there is a suspicion of ML/TF regardless of any threshold; or (e) there are doubts about the veracity of previously obtained identification data. The FI shall not open the account, commence business relations, or perform the transaction if it is unable to comply with CDD requirements.",
                text_ar="يجب على المؤسسات المالية تطبيق تدابير العناية الواجبة عند: (أ) إقامة علاقة عمل؛ (ب) تنفيذ معاملة عرضية تتجاوز 60,000 ريال سعودي؛ (ج) تنفيذ حوالات برقية عرضية تتجاوز 3,000 ريال سعودي؛ (د) وجود اشتباه بغسل أموال أو تمويل إرهاب بغض النظر عن أي حد؛ أو (هـ) وجود شكوك حول صحة بيانات التعريف المحصل عليها سابقاً.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="AML-4.1",
                title="Suspicious Transaction Reporting",
                title_ar="الإبلاغ عن العمليات المشبوهة",
                text="Financial institutions shall promptly report to the Saudi Financial Intelligence Unit (SAFIU) any suspicious transaction, attempted transaction, or activity, regardless of the amount. Reports shall be filed through the designated electronic system. The FI shall maintain all records relating to the STR for a minimum of ten years from the date of filing. Financial institutions shall not tip off the customer or any third party that an STR has been or will be filed.",
                text_ar="يجب على المؤسسات المالية الإبلاغ فوراً إلى الوحدة السعودية للتحريات المالية عن أي عملية مشبوهة أو محاولة عملية أو نشاط بغض النظر عن المبلغ. يجب تقديم البلاغات من خلال النظام الإلكتروني المخصص. يجب على المؤسسة المالية الاحتفاظ بجميع السجلات المتعلقة بالبلاغ لمدة لا تقل عن عشر سنوات من تاريخ تقديمه.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="AML-5.1",
                title="Compliance Officer Appointment",
                title_ar="تعيين مسؤول الالتزام",
                text="Each financial institution shall appoint a qualified compliance officer at a senior management level who shall be responsible for: (a) oversight of the FI's AML/CTF compliance program; (b) reporting to the board or senior management on AML/CTF matters; (c) ensuring that the FI files STRs in a timely manner; (d) acting as the primary point of contact with SAMA and SAFIU on AML/CTF matters; and (e) ensuring adequate AML/CTF training for all relevant staff.",
                text_ar="يجب على كل مؤسسة مالية تعيين مسؤول التزام مؤهل على مستوى الإدارة العليا يكون مسؤولاً عن: (أ) الإشراف على برنامج الالتزام بمكافحة غسل الأموال وتمويل الإرهاب؛ (ب) رفع التقارير لمجلس الإدارة أو الإدارة العليا بشأن مسائل مكافحة غسل الأموال؛ (ج) ضمان تقديم البلاغات في الوقت المناسب؛ (د) التواصل مع البنك المركزي والوحدة السعودية للتحريات المالية؛ و(هـ) ضمان التدريب الكافي لجميع الموظفين المعنيين.",
                provision_type="article",
            ),
        ],
    )
