"""Saudi AML Regulator Pack - Saudi Anti-Money Laundering Law and Implementing Regulations."""
from regulator_packs.base_pack import (
    RegulatorPack, JurisdictionDef, RegulatorDef, SourceDef, TopicDef, ProvisionFixture,
)


def get_pack() -> RegulatorPack:
    return RegulatorPack(
        pack_id="saudi_aml",
        jurisdiction=JurisdictionDef(
            name="Kingdom of Saudi Arabia",
            code="SA",
            name_ar="المملكة العربية السعودية",
            region="Middle East",
        ),
        regulator=RegulatorDef(
            name="Presidency of State Security - Saudi FIU",
            abbreviation="SAFIU",
            name_ar="رئاسة أمن الدولة - الوحدة السعودية للتحريات المالية",
            website="https://www.pss.gov.sa",
            regulator_type="law_enforcement",
            description="Saudi Financial Intelligence Unit under Presidency of State Security, responsible for AML/CTF law enforcement",
            description_ar="الوحدة السعودية للتحريات المالية التابعة لرئاسة أمن الدولة، المسؤولة عن إنفاذ أنظمة مكافحة غسل الأموال وتمويل الإرهاب",
        ),
        sources=[
            SourceDef(
                title="Anti-Money Laundering Law (Royal Decree M/31)",
                title_ar="نظام مكافحة غسل الأموال (المرسوم الملكي م/31)",
                url="https://laws.boe.gov.sa/BoeLaws/Laws/LawDetails/4dc7c959-89da-4578-852e-a9a700f2ed1b/1",
                source_type="law",
                authority_level="tier_1",
                language="ar",
                crawl_frequency="monthly",
                parser_config={"parser_type": "html", "language": "ar"},
            ),
            SourceDef(
                title="Implementing Regulations of the Anti-Money Laundering Law",
                title_ar="اللائحة التنفيذية لنظام مكافحة غسل الأموال",
                url="https://laws.boe.gov.sa/BoeLaws/Laws/LawDetails/e42a5e01-3a7f-4e7d-a8e9-a9a700f2ed63/1",
                source_type="regulation",
                authority_level="tier_1",
                language="ar",
                crawl_frequency="monthly",
                parser_config={"parser_type": "html", "language": "ar"},
            ),
            SourceDef(
                title="Anti-Terrorism and its Financing Law",
                title_ar="نظام مكافحة الإرهاب وتمويله",
                url="https://laws.boe.gov.sa/BoeLaws/Laws/LawDetails/2e0af088-56e7-4baa-8a84-a9a700f2ed43/1",
                source_type="law",
                authority_level="tier_1",
                language="ar",
                crawl_frequency="monthly",
                parser_config={"parser_type": "html", "language": "ar"},
            ),
            SourceDef(
                title="Saudi Arabia Mutual Evaluation Report (FATF/MENAFATF)",
                title_ar="تقرير التقييم المتبادل للمملكة العربية السعودية",
                url="https://www.fatf-gafi.org/en/countries/detail/Saudi-Arabia.html",
                source_type="guidance",
                authority_level="tier_2",
                language="en",
                crawl_frequency="monthly",
                parser_config={"parser_type": "html", "language": "en"},
            ),
        ],
        topics=[
            TopicDef(name="Money Laundering Offenses", category="aml", name_ar="جرائم غسل الأموال"),
            TopicDef(name="Terrorism Financing", category="ctf", name_ar="تمويل الإرهاب"),
            TopicDef(name="Suspicious Transaction Reporting (STR)", category="reporting", name_ar="الإبلاغ عن العمليات المشبوهة"),
            TopicDef(name="Customer Due Diligence (CDD)", category="kyc", name_ar="العناية الواجبة بالعملاء"),
            TopicDef(name="Beneficial Ownership (UBO)", category="kyc", name_ar="الملكية النفعية"),
            TopicDef(name="Record Keeping", category="aml", name_ar="حفظ السجلات"),
            TopicDef(name="Penalties and Sanctions", category="aml", name_ar="العقوبات والجزاءات"),
            TopicDef(name="Designated Non-Financial Businesses (DNFBPs)", category="aml", name_ar="الأعمال والمهن غير المالية المحددة"),
            TopicDef(name="Targeted Financial Sanctions (TFS)", category="sanctions", name_ar="العقوبات المالية المستهدفة"),
            TopicDef(name="Non-Profit Organizations", category="ctf", name_ar="المنظمات غير الربحية"),
        ],
        sample_provisions=[
            ProvisionFixture(
                section_number="Art.2",
                title="Money Laundering Offense",
                title_ar="جريمة غسل الأموال",
                text="Any person who commits any of the following acts shall be guilty of a money laundering offense: (a) converting or transferring funds, knowing that such funds are the proceeds of a criminal offense, for the purpose of concealing or disguising the illicit origin of such funds; (b) concealing or disguising the true nature, source, movement, disposition, or ownership of funds or related rights, knowing that such funds are the proceeds of a criminal offense.",
                text_ar="يعد مرتكباً جريمة غسل الأموال كل من قام بأي من الأفعال الآتية: (أ) تحويل أموال أو نقلها مع علمه بأنها متحصلات جريمة، بغرض إخفاء أو تمويه المصدر غير المشروع لتلك الأموال؛ (ب) إخفاء أو تمويه طبيعة الأموال الحقيقية أو مصدرها أو حركتها أو التصرف فيها أو ملكيتها أو الحقوق المتعلقة بها مع علمه بأنها متحصلات جريمة.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="Art.4",
                title="Customer Due Diligence",
                title_ar="العناية الواجبة بالعملاء",
                text="Financial institutions and designated non-financial businesses and professions shall undertake customer due diligence measures including: identifying the customer and verifying their identity using reliable and independent source documents; identifying the beneficial owner and taking reasonable measures to verify their identity; understanding the nature and purpose of the business relationship; and conducting ongoing due diligence on the business relationship.",
                text_ar="يجب على المؤسسات المالية والأعمال والمهن غير المالية المحددة اتخاذ تدابير العناية الواجبة بالعملاء بما في ذلك: التعرف على هوية العميل والتحقق منها باستخدام وثائق ومستندات موثوقة ومستقلة؛ والتعرف على المستفيد الحقيقي واتخاذ تدابير معقولة للتحقق من هويته؛ وفهم طبيعة علاقة العمل والغرض منها؛ وممارسة العناية الواجبة المستمرة على علاقة العمل.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="Art.9",
                title="Suspicious Transaction Reporting",
                title_ar="الإبلاغ عن العمليات المشبوهة",
                text="Financial institutions and designated non-financial businesses and professions shall promptly report to the General Directorate of Financial Investigation any transaction or attempted transaction, regardless of the amount, if there are reasonable grounds to suspect that the funds involved are the proceeds of criminal activity or are related to money laundering or terrorism financing.",
                text_ar="يجب على المؤسسات المالية والأعمال والمهن غير المالية المحددة الإبلاغ فوراً إلى الإدارة العامة للتحريات المالية عن أي عملية أو محاولة عملية بغض النظر عن مبلغها، إذا كانت هناك أسباب معقولة للاشتباه بأن الأموال المتعلقة بها هي متحصلات نشاط إجرامي أو مرتبطة بغسل الأموال أو تمويل الإرهاب.",
                provision_type="article",
            ),
            ProvisionFixture(
                section_number="Art.16",
                title="Penalties",
                title_ar="العقوبات",
                text="Without prejudice to any more severe penalty provided for in another law, any person convicted of a money laundering offense shall be sentenced to imprisonment for a period not exceeding ten years and a fine not exceeding five million riyals, or either penalty. If the money laundering offense is associated with another crime, the penalty shall be imprisonment for a period not exceeding fifteen years and a fine not exceeding seven million riyals.",
                text_ar="مع عدم الإخلال بأي عقوبة أشد منصوص عليها في نظام آخر، يعاقب كل من يدان بارتكاب جريمة غسل أموال بالسجن مدة لا تزيد على عشر سنوات وبغرامة لا تزيد على خمسة ملايين ريال أو بإحدى هاتين العقوبتين. وإذا اقترنت جريمة غسل الأموال بجريمة أخرى تكون العقوبة السجن مدة لا تزيد على خمس عشرة سنة وغرامة لا تزيد على سبعة ملايين ريال.",
                provision_type="article",
            ),
        ],
    )
